// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcVHSB7WjWK0-kegdRgl5Wr6TqTKgxjQg',
    appId: '1:70183454754:web:6cb0619f7a858e9aade27b',
    messagingSenderId: '70183454754',
    projectId: 'flutter-todo-9f102',
    authDomain: 'flutter-todo-9f102.firebaseapp.com',
    storageBucket: 'flutter-todo-9f102.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJgaZWVRxB-SApTnFre41PwTK8e6OJUNw',
    appId: '1:70183454754:android:bc807c115b5f4216ade27b',
    messagingSenderId: '70183454754',
    projectId: 'flutter-todo-9f102',
    storageBucket: 'flutter-todo-9f102.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv6rozzSOCvTVU2TtTf8QA59tQSDRS_Wc',
    appId: '1:70183454754:ios:d777144a24a11a92ade27b',
    messagingSenderId: '70183454754',
    projectId: 'flutter-todo-9f102',
    storageBucket: 'flutter-todo-9f102.appspot.com',
    iosClientId:
        '70183454754-furpvmqm4gu6kpaunhlr54cgl6ll4l1v.apps.googleusercontent.com',
    iosBundleId: 'todo.app.stg',
  );
}
